import { Dimensions, StyleSheet } from 'react-native'

const { width } = Dimensions.get('window')

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0B0C1E',
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  logoText: {
    color: '#00F5FF',
    fontSize: 24,
    fontWeight: 'bold',
    fontStyle: 'italic',
  },
  balanceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 30,
    paddingRight: 16,
    paddingLeft: 4,
    paddingVertical: 4,
  },
  solIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#1A1B2E',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  balanceLabel: {
    color: '#8E8E93',
    fontSize: 10,
    fontWeight: 'bold',
  },
  balanceValue: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  featuredCard: {
    backgroundColor: '#1A1B2E',
    borderRadius: 20,
    padding: 16,
    marginVertical: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    overflow: 'hidden',
  },
  upcomingIndicator: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: 'rgba(0, 245, 255, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#00F5FF',
  },
  upcomingText: {
    color: '#00F5FF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  teamsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: '100%',
    marginVertical: 20,
  },
  teamInfo: {
    alignItems: 'center',
  },
  teamLogo: {
    width: 60,
    height: 60,
    resizeMode: 'contain',
    marginBottom: 8,
  },
  teamName: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  vsText: {
    color: '#8E8E93',
    fontSize: 18,
    fontWeight: 'bold',
  },
  bottomBar: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.05)',
  },
  gameTime: {
    color: '#8E8E93',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 6,
  },
  liveIndicator: {
    backgroundColor: 'rgba(255, 45, 85, 0.1)',
    borderColor: '#FF2D55',
  },
  liveText: {
    color: '#FF2D55',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 16,
  },
  sectionTitle: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  showAllText: {
    color: '#00F5FF',
    fontSize: 14,
  },
  matchScroll: {
    flexDirection: 'row',
  },
  matchCard: {
    width: width * 0.6,
    backgroundColor: 'rgba(26, 27, 46, 0.8)',
    borderRadius: 16,
    padding: 16,
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  matchIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(0, 245, 255, 0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 245, 255, 0.2)',
  },
  matchTitle: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  matchSubtitle: {
    color: '#8E8E93',
    fontSize: 12,
    marginBottom: 16,
  },
  oddsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  oddItem: {
    flex: 1,
  },
  oddLabel: {
    color: '#8E8E93',
    fontSize: 10,
    marginBottom: 2,
  },
  oddValue: {
    color: '#00F5FF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  betButton: {
    backgroundColor: '#00F5FF',
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
  },
  betButtonText: {
    color: '#0B0C1E',
    fontSize: 12,
    fontWeight: 'bold',
  },
  liveStreamContainer: {
    marginTop: 16,
    backgroundColor: '#1A1B2E',
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  liveStreamHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF2D55',
    marginRight: 8,
  },
  liveStreamTitle: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  webViewWrapper: {
    width: '100%',
    aspectRatio: 16 / 9,
    backgroundColor: 'black',
  },
  webView: {
    flex: 1,
    backgroundColor: 'transparent',
  },
})